# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x12\n\x10ListUsersRequest\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\".\n\x12UpdateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc6\x02\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12<\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x12?\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12?\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=67
  _globals['_CREATEUSERREQUEST']._serialized_start=69
  _globals['_CREATEUSERREQUEST']._serialized_end=117
  _globals['_CREATEUSERRESPONSE']._serialized_start=119
  _globals['_CREATEUSERRESPONSE']._serialized_end=165
  _globals['_GETUSERREQUEST']._serialized_start=167
  _globals['_GETUSERREQUEST']._serialized_end=195
  _globals['_GETUSERRESPONSE']._serialized_start=197
  _globals['_GETUSERRESPONSE']._serialized_end=240
  _globals['_LISTUSERSREQUEST']._serialized_start=242
  _globals['_LISTUSERSREQUEST']._serialized_end=260
  _globals['_LISTUSERSRESPONSE']._serialized_start=262
  _globals['_LISTUSERSRESPONSE']._serialized_end=308
  _globals['_UPDATEUSERREQUEST']._serialized_start=310
  _globals['_UPDATEUSERREQUEST']._serialized_end=370
  _globals['_UPDATEUSERRESPONSE']._serialized_start=372
  _globals['_UPDATEUSERRESPONSE']._serialized_end=418
  _globals['_DELETEUSERREQUEST']._serialized_start=420
  _globals['_DELETEUSERREQUEST']._serialized_end=451
  _globals['_DELETEUSERRESPONSE']._serialized_start=453
  _globals['_DELETEUSERRESPONSE']._serialized_end=490
  _globals['_USERSERVICE']._serialized_start=493
  _globals['_USERSERVICE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
