# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cuser_service\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"6\n\x12\x43reateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\"+\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"3\n\x0fGetUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\"/\n\x10ListUsersRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"E\n\x11ListUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user_service.User\x12\r\n\x05total\x18\x02 \x01(\x05\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"6\n\x12UpdateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe5\x03\n\x0bUserService\x12O\n\nCreateUser\x12\x1f.user_service.CreateUserRequest\x1a .user_service.CreateUserResponse\x12\x46\n\x07GetUser\x12\x1c.user_service.GetUserRequest\x1a\x1d.user_service.GetUserResponse\x12M\n\x0eGetUserbyEmail\x12\x1c.user_service.GetUserRequest\x1a\x1d.user_service.GetUserResponse\x12L\n\tListUsers\x12\x1e.user_service.ListUsersRequest\x1a\x1f.user_service.ListUsersResponse\x12O\n\nUpdateUser\x12\x1f.user_service.UpdateUserRequest\x1a .user_service.UpdateUserResponse\x12O\n\nDeleteUser\x12\x1f.user_service.DeleteUserRequest\x1a .user_service.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=28
  _globals['_USER']._serialized_end=93
  _globals['_CREATEUSERREQUEST']._serialized_start=95
  _globals['_CREATEUSERREQUEST']._serialized_end=161
  _globals['_CREATEUSERRESPONSE']._serialized_start=163
  _globals['_CREATEUSERRESPONSE']._serialized_end=217
  _globals['_GETUSERREQUEST']._serialized_start=219
  _globals['_GETUSERREQUEST']._serialized_end=262
  _globals['_GETUSERRESPONSE']._serialized_start=264
  _globals['_GETUSERRESPONSE']._serialized_end=315
  _globals['_LISTUSERSREQUEST']._serialized_start=317
  _globals['_LISTUSERSREQUEST']._serialized_end=364
  _globals['_LISTUSERSRESPONSE']._serialized_start=366
  _globals['_LISTUSERSRESPONSE']._serialized_end=435
  _globals['_UPDATEUSERREQUEST']._serialized_start=437
  _globals['_UPDATEUSERREQUEST']._serialized_end=497
  _globals['_UPDATEUSERRESPONSE']._serialized_start=499
  _globals['_UPDATEUSERRESPONSE']._serialized_end=553
  _globals['_DELETEUSERREQUEST']._serialized_start=555
  _globals['_DELETEUSERREQUEST']._serialized_end=586
  _globals['_DELETEUSERRESPONSE']._serialized_start=588
  _globals['_DELETEUSERRESPONSE']._serialized_end=625
  _globals['_USERSERVICE']._serialized_start=628
  _globals['_USERSERVICE']._serialized_end=1113
# @@protoc_insertion_point(module_scope)
